apiVersion: v1
kind: Service
metadata:
  name: yolo-db-service
  namespace: yolo-db
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: yolo-db
  clusterIP: None  # Headless service for StatefulSet
