apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-service
  namespace: yolo-backend
spec:
  type: LoadBalancer
  selector:
    app: yolo-backend
  ports:
    - port: 5000
      targetPort: 5000
